name: bzip2
version: 0.0.5
author: Hadi Moshayedi <hadi@moshayedi.net>
description: bzip2 compression algorithm
homepage: https://github.com/pykello/dartlang-bzip2
dev_dependencies:
  unittest: 0.11.1
